package com.aitem.connect.enums;

import lombok.Getter;

public enum OrderStatus {
    IN_CART,
    CHECKED_OUT,
    PAYMENT_SUCCESSFUL,
    PAYMENT_FAIL,
    WAITING_ACCEPTANCE_FROM_DRIVER,
    DRIVER_ACCEPTED,
    DRIVER_DECLINED,
    DELIVERED,

    LOOKING_FOR_DRIVER,
    SUBMITTED_FOR_PAYMENT,
    CLERK_ASSIGNED_ORDER_TO_DRIVER;
}
