CREATE TABLE IF NOT EXISTS authentication (
    id VARCHAR(100) PRIMARY KEY,
    token VARCHAR(400) NOT NULL,
    user_id VARCHAR(100) NOT NULL UNIQUE,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expire_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
