CREATE TABLE IF NOT EXISTS cart (
    id VARCHAR(128) PRIMARY KEY,
    order_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    store_id VARCHAR(128),
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(128) NOT NULL
)
