CREATE TABLE IF NOT EXISTS zip_store (
    id VARCHAR(128) PRIMARY KEY,
    zip VARCHAR(128) NOT NULL,
    store_id VARCHAR(128) NOT NULL,
    distance VARCHAR(24),
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
