CREATE TABLE IF NOT EXISTS zip_neighbour (
    id VARCHAR(128) PRIMARY KEY,
    zip VARCHAR(128) NOT NULL,
    driver_id VARCHAR(128) NOT NULL,
    distance VARCHAR(24) NOT NULL,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
